{% set name = "lz" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lz-{{ version }}.tar.gz
  sha256: 6b816276e140389b93234da7b6d767380b9a9eba50c725a9da471d0bf5a0a007

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - paradigm <1.0,>=0.6.2
    - reprit <1.0,>=0.8.0
    - typing-extensions <5.0,>=4.4.0

test:
  imports:
    - lz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lycantropos/lz/
  summary: Functional utilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
